### PR TITLE
Adding columns to markdown parser

### PR DESCRIPTION
**Pull request by hgoldstein**
See new example. This is pretty close to "clean" w.r.t. how marked is designed I think. There's some weirdness involving how lists are parsed. For instance the following:
```
(|
%
# Foo
* Bar
  * Baz
%
# Zardoz
 * Jim
  * Jam
|)
```
Will not display as expected. I should investigage before merging. It might be regex voodoo.

### CODE REVIEW

**Comment by orangeturtle739** [comment]
It's because lists don't terminate across column borders. If you add one blank line, it works:
```
(|
%
# Foo
* Bar
  * Baz

%
# Zardoz
 * Jim
  * Jam
|)
```

**Comment by hgoldstein** [comment]
Yup that's what I found as well: the added `columns.md` looks like what you have.

**Comment by hgoldstein** [comment]
Specifically this is the diff between having a space after the list versus not having a space after the list. I'm playing around with the `list` regex.
vimdiff of space vs. no space

**Comment by orangeturtle739** [comment]
Just require the space after list. Markdown has always been finicky with spacing.

**Comment by hgoldstein** [comment]
Yeah; let me update the README quick to include the column syntax.

**Review by orangeturtle739 — APPROVED** [review]
:unicorn:

**Pull request merged**
